### ISSUE TITLE
Link to Android download is broken

### ISSUE THREAD

**Issue by nanodino** [boris-behav-obs/boris-behav-obs.github.io#1] opened 2024-04-17 16:17 UTC
[Download BORIS App v. {{ no such element: dict object['app_version'] }}](https://github.com/olivierfriard/BORIS-App/releases/tag/v%20%7B%7B%20no%20such%20element:%20dict%20object['app_version']%20%7D%7D)

This can be easily circumvented by looking at the version for the latest release and replacing the `no such element...` text but still

**Comment by olivierfriard** [comment] 2024-04-17 16:47
The issue is fixed now.
Thank you for reporting this

**Closed as completed by olivierfriard** 2024-04-17 16:47 UTC
